#!/usr/bin/env bash
set -euo pipefail

ROOT="$HOME/projects/ross-llm"
cd "$ROOT"

echo "🧰 Setting up blueprint helper tools under $ROOT"

mkdir -p scripts
mkdir -p docs/blueprint/status

########################################
# Tool 1: Snapshot profiles -> markdown
########################################
cat > scripts/snapshot_profiles.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$HOME/projects/ross-llm}"
cd "$ROOT"

PROFILE_DIR="apps/orchestrator/profiles"
OUT_FILE="docs/blueprint/status/profiles_registry.md"

if [ ! -d "$PROFILE_DIR" ]; then
  echo "❌ Profile dir not found: $PROFILE_DIR"
  exit 1
fi

mkdir -p "$(dirname "$OUT_FILE")"

echo "📓 Building profiles registry from $PROFILE_DIR → $OUT_FILE"

{
  echo "# Ross-LLM Profiles Registry"
  echo
  echo "_Auto-generated by scripts/snapshot_profiles.sh – do not edit by hand._"
  echo
  echo "| Profile | Description | Source |"
  echo "|---------|-------------|--------|"
} > "$OUT_FILE"

for f in "$PROFILE_DIR"/*.yaml; do
  [ -e "$f" ] || continue
  name="$(basename "$f" .yaml)"

  # Try to pull a description line if present
  desc="$(grep -m1 '^description:' "$f" 2>/dev/null | sed 's/^description:\s*//')"
  if [ -z "$desc" ]; then
    desc="(no description in YAML)"
  fi

  # Escape pipe characters in description
  desc_escaped="${desc//|/\\|}"

  echo "| \`$name\` | $desc_escaped | \`$f\` |" >> "$OUT_FILE"
done

echo "✅ Updated $OUT_FILE"
SH

chmod +x scripts/snapshot_profiles.sh

########################################
# Tool 2: Blueprint status overview
########################################
cat > scripts/blueprint_status.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$HOME/projects/ross-llm}"
cd "$ROOT"

echo "🧭 Ross-LLM Blueprint Status"
echo "Root: $ROOT"
echo

#########################
# Pillar headings
#########################
echo "=== Pillars ==="
for f in docs/blueprint/core_os/01_core_os_overview.md \
         docs/blueprint/shopify_agent/02_shopify_agent_overview.md \
         docs/blueprint/devops_agent/03_devops_agent_overview.md \
         docs/blueprint/life_archive/04_life_archive_overview.md \
         docs/blueprint/swarm/05_swarm_overview.md
do
  if [ -f "$f" ]; then
    title="$(grep -m1 '^# ' "$f" | sed 's/^# //')"
    printf " • %s  (%s)\n" "$title" "$(basename "$f")"
  fi
done
echo

#########################
# Profiles (if registry exists)
#########################
if [ -f docs/blueprint/status/profiles_registry.md ]; then
  echo "=== Profiles (from profiles_registry.md) ==="
  # Show just the table body, skip header lines
  awk 'NR>4 {print}' docs/blueprint/status/profiles_registry.md
  echo
else
  echo "ℹ️ No profiles_registry.md yet. Run:"
  echo "   ./scripts/snapshot_profiles.sh"
  echo
fi

#########################
# Backlog NOW section
#########################
BACKLOG="docs/blueprint/status/roadmap_backlog.md"
if [ -f "$BACKLOG" ]; then
  echo "=== NOW Backlog ==="
  awk '
    /## NOW/ {flag=1; next}
    /## NEXT/ {flag=0}
    flag {print}
  ' "$BACKLOG"
  echo
else
  echo "ℹ️ No roadmap_backlog.md found."
  echo
fi

echo "Tip: Use:"
echo "  ./scripts/snapshot_profiles.sh   # refresh profile list"
echo "  ./scripts/blueprint_status.sh    # view this dashboard"
SH

chmod +x scripts/blueprint_status.sh

########################################
# Tool 3: One-line dashboard alias helper
########################################
cat > scripts/print_alias_hint.sh <<'SH'
#!/usr/bin/env bash
set -euo pipefail

cat <<'TXT'
You can add this to your shell config (~/.zshrc or ~/.bashrc):

  alias rblue='cd ~/projects/ross-llm && ./scripts/blueprint_status.sh'

Then just run:

  rblue

…to see your current pillars, profiles, and NOW backlog.
TXT
SH

chmod +x scripts/print_alias_hint.sh

echo "✅ Tools created:"
echo "  • scripts/snapshot_profiles.sh"
echo "  • scripts/blueprint_status.sh"
echo "  • scripts/print_alias_hint.sh"
