#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-$HOME/projects/ross-llm}"
cd "$ROOT"

PROFILE_DIR="apps/orchestrator/profiles"
OUT_FILE="docs/blueprint/status/profiles_registry.md"

if [ ! -d "$PROFILE_DIR" ]; then
  echo "❌ Profile dir not found: $PROFILE_DIR"
  exit 1
fi

mkdir -p "$(dirname "$OUT_FILE")"

echo "📓 Building profiles registry from $PROFILE_DIR → $OUT_FILE"

{
  echo "# Ross-LLM Profiles Registry"
  echo
  echo "_Auto-generated by scripts/snapshot_profiles.sh – do not edit by hand._"
  echo
  echo "| Profile | Description | Source |"
  echo "|---------|-------------|--------|"
} > "$OUT_FILE"

for f in "$PROFILE_DIR"/*.yaml; do
  [ -e "$f" ] || continue
  name="$(basename "$f" .yaml)"

  # Try to pull a description line if present
  desc="$(grep -m1 '^description:' "$f" 2>/dev/null | sed 's/^description:\s*//')"
  if [ -z "$desc" ]; then
    desc="(no description in YAML)"
  fi

  # Escape pipe characters in description
  desc_escaped="${desc//|/\\|}"

  echo "| \`$name\` | $desc_escaped | \`$f\` |" >> "$OUT_FILE"
done

echo "✅ Updated $OUT_FILE"
